[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]
excludes = ["tmp/*"]

[formatter.ocaml]
command = "ocamlformat"
options = ["--inplace"]
includes = ["*.ml"]
excludes = ["data/*", "tmp/*"]

[formatter.python]
command = "black"
includes = ["*.py"]
excludes = ["data/*", "tmp/*"]

[formatter.shell]
command = "sh"
options = ["-eucx", """
if [[ $# -le 0 ]]; then exit 0; fi
shfmt -i 4 -s -w "$@"
""", "--"]
includes = ["*.sh"]
excludes = ["tmp/*"]
